name : CI CD run Tests
on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
    run-unit-test : 
      runs-on: ubunto-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7 

        - name: run-unit-test 
          run: mvn test



